- id: '1756309707631'
  alias: 'TV accesa cornice '
  description: ''
  triggers:
  - type: turned_on
    device_id: 25cfd7469f060c88f77f8721bd90ce90
    entity_id: 8c04f8d364294d73fa2b6f0c720f1fa1
    domain: remote
    trigger: device
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      device_id: e713e0826211997dce803385fc048702
  mode: single
- id: '1756309742361'
  alias: TV spenta cornice
  description: ''
  triggers:
  - type: turned_off
    device_id: 25cfd7469f060c88f77f8721bd90ce90
    entity_id: 8c04f8d364294d73fa2b6f0c720f1fa1
    domain: remote
    trigger: device
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      device_id: e713e0826211997dce803385fc048702
  mode: single
- id: ha_git_nightly_commit
  alias: HA Git Nightly Commit
  description: Commit HA config and push to remote
  mode: single
  trigger:
  - platform: time
    at: 03:30:00
  condition: []
  action:
  - service: shell_command.ha_git_nightly_commit
- id: '1760187555607'
  alias: Accensione Luci Esterne Tramonto
  description: ''
  triggers:
  - trigger: sun
    event: sunset
    offset: '900'
  conditions: []
  actions:
  - type: turn_on
    device_id: 28c5a24fad7e3978faaea346f7a38d5f
    entity_id: fa927b675db9469dd1c11d9e2b76bbd4
    domain: switch
  mode: single
- id: '1760187595023'
  alias: Spegnimento Luci Esterne Alba
  description: ''
  triggers:
  - trigger: sun
    event: sunrise
    offset: 0
  conditions: []
  actions:
  - type: turn_off
    device_id: 28c5a24fad7e3978faaea346f7a38d5f
    entity_id: fa927b675db9469dd1c11d9e2b76bbd4
    domain: switch
  mode: single
- id: restore_irrigazione_programma
  alias: Ripristina programma irrigazione all'avvio
  trigger:
  - platform: homeassistant
    event: start
  action:
  - delay: 00:00:30
  - service: input_select.select_option
    target:
      entity_id: input_select.irrigazione_programma_attivo
    data:
      option: '{{ states(''input_text.last_irrigation_program'') }}'
  mode: single
- id: aggiorna_helper_irrigazione_cambio_programma
  alias: Aggiorna helper irrigazione ad ogni cambio programma
  trigger:
  - platform: state
    entity_id: input_select.irrigazione_programma_attivo
  action:
  - service: input_text.set_value
    target:
      entity_id: input_text.prev_irrigation_program
    data:
      value: '{{ states(''input_text.last_irrigation_program'') }}'
  - service: input_text.set_value
    target:
      entity_id: input_text.last_irrigation_program
    data:
      value: '{{ states(''input_select.irrigazione_programma_attivo'') }}'
  mode: single
- id: '1760614649374'
  alias: StronzoDiMerdaDopo1MinutoSettaProgrammaIrrigazione
  description: ''
  triggers:
  - trigger: homeassistant
    event: start
  conditions: []
  actions:
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - action: input_select.select_option
    target:
      entity_id: input_select.irrigazione_programma_attivo
    data:
      option: Dummy
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - action: input_select.select_option
    target:
      entity_id: input_select.irrigazione_programma_attivo
    data:
      option: '{{ states(''input_text.prev_irrigation_program'') }}'
  mode: single
- id: '1760956597855'
  alias: Planta Irrigazione Sync quando piove (per area)
  description: Esegue il watering su tutte le piante nelle aree Giardino e Aiuola
    quando piove
  triggers:
  - entity_id: sensor.pirateweather2_liquid_accumulation_0d
    above: 2
    trigger: numeric_state
  actions:
  - target:
      entity_id: "{% set aree = ['Giardino', 'Aiuola', 'Terrazzo Tetto'] %} {% set
        all_entities = expand(aree | map('area_entities') | sum(start=[])) %} {{ all_entities\n
        \   | selectattr('entity_id', 'search', 'complete_watering')\n    | map(attribute='entity_id')\n
        \   | list }}\n"
    action: button.press
    data: {}
  mode: single
- id: '1760958500734'
  alias: Planta Irrigazione Aiuola Sync
  description: Esegue il watering su tutte le piante nell'area Aiuola quando si accende
    lo switch Shelly
  triggers:
  - entity_id: switch.shelly_irrigazione_aiuola
    to: 'on'
    trigger: state
  actions:
  - target:
      entity_id: "{{ expand(area_entities('Aiuola'))\n    | selectattr('entity_id',
        'search', 'complete_watering')\n    | map(attribute='entity_id')\n    | list
        }}\n"
    action: button.press
    data: {}
  mode: single
- id: '1760964154108'
  alias: Planta Prato irrigazione sync
  description: Esegue il watering su tutte le piante nelle aree Giardino e Aiuola
    quando piove
  triggers:
  - type: turned_on
    device_id: 6a0af23c74e2af95b59e740ec0a821c2
    entity_id: da1fdccb76e5fcced3466491021c4506
    domain: switch
    trigger: device
  conditions: []
  actions:
  - target:
      entity_id: "{{ expand(area_entities('Giardino'))\n    | selectattr('entity_id',
        'search', 'complete_watering')\n    | map(attribute='entity_id')\n    | list
        }}\n"
    action: button.press
    data: {}
  mode: single
- id: '1761126192357'
  alias: Allarme Blocco Fotovoltaico Paderno
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.abb_powerone_pvi_sunspec_106823_3p74_0724_ac_power
    to: unavailable
    for:
      hours: 0
      minutes: 10
      seconds: 0
  conditions:
  - condition: sun
    before: sunset
    after: sunrise
  actions:
  - action: notify.gmail_notify
    metadata: {}
    data:
      title: Attenzione! Blocco Fotovoltaico Paderno
      message: Ciao Andrea e Luca, il fotovoltaico a Paderno sembra essere in blocco.
        Controllo immediato!
  mode: single
