- id: '1756309707631'
  alias: 'TV accesa cornice '
  description: ''
  triggers:
  - type: turned_on
    device_id: 25cfd7469f060c88f77f8721bd90ce90
    entity_id: 8c04f8d364294d73fa2b6f0c720f1fa1
    domain: remote
    trigger: device
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      device_id: e713e0826211997dce803385fc048702
  mode: single

- id: '1756309742361'
  alias: TV spenta cornice
  description: ''
  triggers:
  - type: turned_off
    device_id: 25cfd7469f060c88f77f8721bd90ce90
    entity_id: 8c04f8d364294d73fa2b6f0c720f1fa1
    domain: remote
    trigger: device
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      device_id: e713e0826211997dce803385fc048702
  mode: single

- id: ha_git_nightly_commit
  alias: HA Git Nightly Commit
  description: Commit HA config and push to remote
  mode: single
  trigger:
    - platform: time
      at: "03:30:00"
  condition: []
  action:
    - service: shell_command.ha_git_nightly_commit