# Put this into automations.yaml or under /config/automations/
automation:
  - id: ha_git_nightly_commit
    alias: HA Git Nightly Commit
    description: Commit HA config and push to remote
    mode: single
    trigger:
      - platform: time
        at: "03:30:00"
    action:
      - service: shell_command.ha_git_nightly_commit
