# irrigazione_applica_programma.yaml
#
# This automation applies the selected Irrigation Unlimited program
# and NO LONGER forces "Primavera" at startup.
# It triggers on HA start and whenever the selection changes.
#
# Requires:
#   input_select.irrigazione_programma    (your helper with: Avvio prato, Primavera, Autunno, Estate)
#   binary_sensor.irrigation_unlimited_c1_s1 .. s4 (your IU sequences)
#
# Place this file in /config/packages/ or include under 'automation: !include ...'

automation:
  - alias: "Irrigazione: applica programma IU selezionato"
    id: irrigazione_applica_programma_iu
    mode: restart
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: input_select.irrigazione_programma
    variables:
      sel: "{{ states('input_select.irrigazione_programma') }}"
    action:
      # On HA start, wait a few seconds so the restore package can set the input_select first
      - choose:
          - conditions: "{{ trigger.platform == 'homeassistant' }}"
            sequence:
              - delay: "00:00:04"
        default: []
      # Disable all sequences first
      - service: irrigation_unlimited.disable
        data:
          entity_id:
            - binary_sensor.irrigation_unlimited_c1_s1
            - binary_sensor.irrigation_unlimited_c1_s2
            - binary_sensor.irrigation_unlimited_c1_s3
            - binary_sensor.irrigation_unlimited_c1_s4
      # Enable the selected one
      - choose:
          - conditions: "{{ sel == 'Avvio prato' }}"
            sequence:
              - service: irrigation_unlimited.enable
                data:
                  entity_id: binary_sensor.irrigation_unlimited_c1_s1
          - conditions: "{{ sel == 'Primavera' }}"
            sequence:
              - service: irrigation_unlimited.enable
                data:
                  entity_id: binary_sensor.irrigation_unlimited_c1_s2
          - conditions: "{{ sel == 'Autunno' }}"
            sequence:
              - service: irrigation_unlimited.enable
                data:
                  entity_id: binary_sensor.irrigation_unlimited_c1_s3
          - conditions: "{{ sel == 'Estate' }}"
            sequence:
              - service: irrigation_unlimited.enable
                data:
                  entity_id: binary_sensor.irrigation_unlimited_c1_s4
        default: []
