# zz_irrigazione_persist.yaml
#
# Package to persist and restore the selected Irrigation Unlimited program across HA restarts.
# Drop this file into /config/packages/ (or include it via packages: in configuration.yaml).
# It does NOT redefine your input_select; it only remembers its value and restores it at startup.
#
# Entities used:
#   input_select.irrigazione_programma   (must already exist in your setup)
#
# What it adds:
#   input_text.irrigazione_programma_last
#   two automations to save/restore the selected program

homeassistant:
  customize: {}

input_text:
  irrigazione_programma_last:
    name: Last selected irrigation program
    max: 50
    # do NOT set 'initial' so HA restores the last state automatically

automation:
  - alias: "Irrigation: remember selected program on change"
    id: irrigation_remember_selected_program
    mode: queued
    max: 10
    trigger:
      - platform: state
        entity_id: input_select.irrigazione_programma
    condition: []
    action:
      - service: input_text.set_value
        target:
          entity_id: input_text.irrigazione_programma_last
        data:
          value: "{{ trigger.to_state.state }}"

  - alias: "Irrigation: restore selected program at startup"
    id: irrigation_restore_selected_program_on_start
    mode: restart
    trigger:
      - platform: homeassistant
        event: start
    # Wait a couple of seconds so any other startup automations finish first
    action:
      - delay: "00:00:03"
      - choose:
          - conditions:
              - condition: template
                value_template: >-
                  {{ states('input_text.irrigazione_programma_last') | lower not in ['unknown','unavailable','', none] }}
            sequence:
              - service: input_select.select_option
                target:
                  entity_id: input_select.irrigazione_programma
                data:
                  option: "{{ states('input_text.irrigazione_programma_last') }}"
        default: []
